In [1]:
import blip.utils.utils as utils
from blip.utils.utils import get_array_names
from blip.utils.utils import get_shape_dictionary
import numpy as np

In [28]:
one_file = "/Users/rivera/Documents/Code/Python/ML/blip_stuff/BlipModels/protodune/data/protodune_mc_0/view2_tpc1.npz"
get_array_names(one_file)

['features',
 'classes',
 'clusters',
 'meta',
 '10.0_6_particle',
 '10.0_6_reductions',
 '10.0_6_cluster_ids',
 '10.0_6_cluster_indices']

In [65]:
# -- load in file and get info
loaded_file = np.load(one_file, allow_pickle=True)
loaded_arrays = {
        key: loaded_file[key] for key in loaded_file.files
    }
print(loaded_arrays)

{'features': array([array([[2.08000000e+03, 2.12000000e+02, 1.47118796e-06],
              [2.08000000e+03, 2.13000000e+02, 1.47118796e-06],
              [2.08000000e+03, 2.14000000e+02, 1.61830676e-06],
              ...,
              [2.55800000e+03, 4.84100000e+03, 5.88475184e-06],
              [2.55800000e+03, 4.84200000e+03, 3.60441050e-06],
              [2.55800000e+03, 4.84300000e+03, 2.28034134e-06]]),
       array([[2.08000000e+03, 2.12300000e+03, 4.86565382e-07],
              [2.08000000e+03, 2.12400000e+03, 3.64924037e-07],
              [2.08000000e+03, 2.12500000e+03, 3.64924037e-07],
              ...,
              [2.55800000e+03, 5.99600000e+03, 0.00000000e+00],
              [2.55800000e+03, 5.99700000e+03, 0.00000000e+00],
              [2.55800000e+03, 5.99800000e+03, 1.21641346e-07]]),
       array([[2.08000000e+03, 3.58000000e+02, 3.77173035e-07],
              [2.08000000e+03, 3.59000000e+02, 4.71466294e-07],
              [2.08000000e+03, 3.60000000e+02, 4.

In [67]:
meta_set = loaded_arrays['meta']
print(meta_set)

{'who_created': 'rivera', 'when_created': '06-15-2023-15:10:42', 'where_created': 'manannan.lanl.gov', 'num_events': 5, 'view': 2, 'features': {'channel': 0, 'tdc': 1, 'adc': 2}, 'classes': {'source': 0, 'shape': 1, 'particle': 2}, 'clusters': {'shape': 0, 'particle': 1}, 'source_labels': {-1: 'undefined', 0: 'noise', 1: 'cosmics', 2: 'beam', 3: 'radiological', 4: 'pns', 5: 'hepevt', 6: 'mixed'}, 'source_points': {-1: 0, 0: 0, 1: 483695, 2: 0, 3: 20636, 4: 7975, 5: 0, 6: 0}, 'shape_labels': {-1: 'undefined', 0: 'noise', 1: 'blip', 2: 'track', 3: 'shower', 4: 'neutron_capture', 5: 'mixed'}, 'shape_points': {-1: 0, 0: 0, 1: 21645, 2: 342305, 3: 145444, 4: 2912, 5: 0}, 'particle_labels': {-1: 'undefined', 0: 'noise', 1: 'muon', 2: 'anti-muon', 3: 'pi0', 4: 'pi+', 5: 'pi-', 6: 'K0', 7: 'K+', 8: 'K-', 9: 'proton', 10: 'delta', 11: 'michel', 12: 'e-shower', 13: 'e+shower', 14: 'gamma_shower', 15: 'capture_gamma', 16: 'capture_gamma_474', 17: 'capture_gamma_336', 18: 'capture_gamma_256', 19: 

In [74]:
classes_set = loaded_arrays['classes']
print(len(classes_set[0]))
print(classes_set[0])
print(classes_set[0].shape)

125314
[[1 2 1]
 [1 2 1]
 [1 2 1]
 ...
 [1 2 1]
 [1 2 1]
 [1 2 1]]
(125314, 3)


In [30]:
len(loaded_arrays)

8

In [31]:
# -- these are the points or waveform features identified as blips in the event
features_set = loaded_arrays['features']
print(len(features_set[0]))
print(features_set[0].shape)

125314
(125314, 3)


In [32]:
# -- these are the (channel #, tdc) for a given view
clusters_set = loaded_arrays['clusters']
print(len(clusters_set[0]))
print(clusters_set[0].shape)

125314
(125314, 2)


In [34]:
# -- don't need this for now
#reduction_set = loaded_arrays['10.0_6_reductions']
#print(reduction_set.shape)
#print(reduction_set)

In [35]:
# -- the cluster_id is the cluster label given by DBScan (to each point in the original features array (chan,tdc,adc))
# -- cluster_id's are sequential
# -- this represents how DBSCAN "clusters" the points(or features) into clusters
cluster_set = loaded_arrays['10.0_6_cluster_ids']
print(cluster_set.shape)
print(cluster_set)
print(len(cluster_set[0]))

(5,)
[array([ -1,  -1,  -1, ..., 216, 216, 216])
 array([  0,   0,   0, ..., 183, 183, 183])
 array([-1, -1, -1, ..., -1, -1, -1])
 array([  0,   0,   0, ..., 222, 222, 222])
 array([  0,   0,   0, ..., 199, 199, 199])]
4368


In [50]:
# -- cluster_indices are the indices of the data_{ii}.pt files associated w/ each cluster_id from each event
# -- this represents the mapping from cluster_id to pytorch (pre-processed) files.
# -- Note: these are numbered uniquely across the entire training dataset,
#    so the pt_index picks up where the previous event left off.
cluster_ind_set = loaded_arrays['10.0_6_cluster_indices']
print(f"The length of the cluster_ind_set for evt=1 is : {len(cluster_ind_set[0])}")
print(f"The shape for the cluster_ind_set for evt=1 is : {cluster_ind_set.shape}")
print(cluster_ind_set)

The length of the cluster_ind_set for evt=1 is : 218
The shape for the cluster_ind_set for evt=1 is : (5,)
[list([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 1

In [42]:
# -- these are the prediction (probabilities) for each particle type
# -- There is one array for each cluster (data_ii.pt file) w/ one entry per particle class defined
particle_set=loaded_arrays['10.0_6_particle']
print(len(particle_set[0]))
print(particle_set[0].shape)
print(particle_set)

218
(218, 1, 32)
[array([[[0.030686207115650177, 0.03069087490439415,
          0.030686212703585625, ..., 0.03065212070941925,
          0.03068728744983673, 0.030697859823703766]],

        [[0.030686207115650177, 0.03069087490439415,
          0.030686212703585625, ..., 0.03065212070941925,
          0.03068728744983673, 0.030697859823703766]],

        [[0.030686207115650177, 0.03069087490439415,
          0.030686212703585625, ..., 0.03065212070941925,
          0.03068728744983673, 0.030697859823703766]],

        ...,

        [[0.030686207115650177, 0.03069087490439415,
          0.030686212703585625, ..., 0.03065212070941925,
          0.03068728744983673, 0.030697859823703766]],

        [[0.030686207115650177, 0.03069087490439415,
          0.030686212703585625, ..., 0.03065212070941925,
          0.03068728744983673, 0.030697859823703766]],

        [[0.030686207115650177, 0.03069087490439415,
          0.030686212703585625, ..., 0.03065212070941925,
          0.03068728744

In [59]:
# -- add up the probabilities to make sure
i=0
totals=[]
for probs in particle_set[0]:
    total = np.sum(probs)
    totals.append(total)
    if (i==0):
        print(f"total for first array = {total}")
    
    i+=1
    

total for first array = 0.9999999608844519


In [61]:
print(totals)

[0.9999999608844519, 0.9999999608844519, 0.9999999608844519, 0.9999999608844519, 0.9999999608844519, 0.9999999608844519, 0.9999999608844519, 0.9999999608844519, 0.9999999608844519, 0.9999999608844519, 0.9999999608844519, 0.9999999608844519, 0.9999999608844519, 0.9999999608844519, 0.9999999608844519, 0.9999999608844519, 0.9999999608844519, 0.9999999608844519, 0.9999999608844519, 0.9999999608844519, 0.9999999608844519, 0.9999999608844519, 0.9999999608844519, 0.9999999608844519, 0.9999999608844519, 0.9999999608844519, 0.9999999608844519, 0.9999999608844519, 0.9999999608844519, 0.9999999608844519, 0.9999999608844519, 0.9999999608844519, 0.9999999608844519, 0.9999999608844519, 0.9999999608844519, 0.9999999608844519, 0.9999999608844519, 0.9999999608844519, 0.9999999608844519, 0.9999999608844519, 0.9999999608844519, 0.9999999608844519, 0.9999999608844519, 0.9999999608844519, 0.9999999608844519, 0.9999999608844519, 0.9999999608844519, 0.9999999608844519, 0.9999999608844519, 0.9999999608844519,

In [60]:
#cluster_results_file = "/Users/rivera/Documents/Code/Python/ML/blip_stuff/BlipModels/protodune/data/cluster_results.npz"
#get_array_names(cluster_results_file)

In [75]:
import uproot

In [76]:
filename = '/Users/rivera/Documents/Code/Python/ML/blip_stuff/BlipModels/protodune/data/protodune_mc_0.root'
file = uproot.open(filename)

filename

'/Users/rivera/Documents/Code/Python/ML/blip_stuff/BlipModels/protodune/data/protodune_mc_0.root'